### PR TITLE
Profile site

### PR DESCRIPTION
**Pull request by bpgrabi**
All previous comments, errors etc are done.

### CODE REVIEW

**Comment by PiotrWodecki** [comment]
- tmp email is visible when registering
image

- username appears editable but is not and shouldn't be
image

- when changing the email if we change it twice - it's possible to click on the old link and the email will change to the second email
e.g.:
admin@admin.com --> change to admin1@admin.com --> Change to admin2@admin.com --> Click on link sent to admin1@admin.com --> the email will be changed to admin2@admin.com, it should say that the link has expired instead

- Lack of crispy forms tags makes the forms look ugly
image

- After deleting the account the login form is missing
image

**Review by PiotrWodecki — CHANGES_REQUESTED** [review]
Please take a look at the comment above

**Comment by bpgrabi** [comment]
- tmp email is visible when registering - done
- username appears editable but is not and shouldn't be - done
- when changing the email if we change it twice - it's possible to click on the old link and the email will change to the second email - I was sure that's exactly what the token is for
- Lack of crispy forms tags makes the forms look ugly - with me it looks like this: 
image

- After deleting the account the login form is missing - done

**Comment by bpgrabi** [comment]
@PiotrWodecki 
```when changing the email if we change it twice - it's possible to click on the old link and the email will change to the second email```
Please check it now. I added var-tmp_email to hash 
image
If it works the way I think it should work.

**Pull request closed without merging**
